/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

import java.util.*;

public class Library {

    public static int[] roll(int n) {
        int[] number = new int[n];
        for (int i = 0; i < number.length; i++) {
            int random = (int) Math.ceil(Math.random() * 6);
            number[i]=random;
        }
        System.out.println(Arrays.toString(number) );

//        for (int i = 0; i < n; i++){
//            System.out.print(number[i] + ", ");
//        }
//
//        System.out.println("\n");
        return number;
    }

    public static boolean containsDuplicates(int[] arr) {

        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }
            }
        }
        return false;

    }

    public static double avgArray(int[] array) {
        double sum = 0;
        for (int value : array) {
            sum += value;
        }
        return (sum / array.length);
    }

    public static int[] arrayOfArrays(int [][] arr){

        double [] avarges =new double[arr.length];
        double Avg =0;
        for (int i=0;i<arr.length;i++){
            double sum = 0;
            double arrLength=0;
            for (int j =0;j<arr[i].length;j++){
                sum += arr[i][j];
            }
            avarges[i]=sum/arr[i].length;
        }
        Avg=avarges[0];
        int lewestArryAvg=0;
        for (int i = 1; i < avarges.length; i++) {
            if (avarges[i] < Avg) {
                Avg = avarges[i];
                lewestArryAvg=i;
            }
        }
        return arr[lewestArryAvg];
    }
    public boolean someLibraryMethod() {
        return true;

    }
    public static String analyzeWeathData(int[][] data) {
        HashSet<Integer> Tempratuer = new HashSet<>();
        for (int i = 0; i < data.length; i++) {
            for (int temp : data[i]) {
                Tempratuer.add(temp);
            }
        }

        String minTemp = "Low Temperature " + Collections.min(Tempratuer);
        String maxTemp = "\nHigh Temperature " + Collections.max(Tempratuer);
        String neverSawTemp = "";
        for (int i = Collections.min(Tempratuer); i < Collections.max(Tempratuer); i++) {
            if (!Tempratuer.contains(i)) {
                neverSawTemp += "\nNever saw temperature: " + i;

            }
        }
        return minTemp + maxTemp + neverSawTemp;

    }


    public static String tally(List<String> votes) {
        if (votes.isEmpty()) return "0";

        HashSet<String> votedvalue = new HashSet<>();
        votedvalue.addAll(votes);

        int numVotes = 0;
        String winner = null;

        for (String value : votedvalue) {
            int count = Collections.frequency(votes, value);
            if (numVotes < count) {
                numVotes = count;

                winner = "\n"+ value + " received the most votes!";
            }
        }

        return winner;
    }
}