/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab6;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

            Restaurant restaurant =new Restaurant("irbid","$$");
            System.out.println(restaurant);

            Review review= new Review("nice restaurant","abrar",3);
        Review review1= new Review("good restaurant","abrar",2);
        Review review2= new Review("perfect restaurant","abrar",1);
        Review review3= new Review("bad restaurant","abrar",0);
        Review review4= new Review("nice restaurant","abrar",4);
        Review review5= new Review("wonderful restaurant","abrar",5);
        Review review6= new Review("bad restaurant","abrar",3);
        restaurant.addReview(review);
        restaurant.addReview(review1);
        restaurant.addReview(review2);
        restaurant.addReview(review3);
        restaurant.addReview(review4);
        restaurant.addReview(review5);
        restaurant.addReview(review6);
        System.out.println(restaurant);




    }
}
