/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;


import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Path newpath = Paths.get("app/src/main/resources/gates.js");

        System.out.println(ReadFiler(newpath));
    }

    public static String ReadFiler(Path newpath) {
        String line = "";
        String errorMSGs = "";
        int lineNum=1;

            try (
                    BufferedReader bufferedReader = Files.newBufferedReader(newpath)
            ) {
                while ((line = bufferedReader.readLine()) != null) {
                    if (!(line.isBlank() || line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else") || line.endsWith(";")))
                        errorMSGs += "Line " + lineNum + ": Missing semicolon.\n";
                    lineNum++;
                }
            } catch (IOException ioException) {
                System.out.println(ioException.getMessage());
            }
            return errorMSGs;
    }


}
